### ISSUE TITLE
Android Things

### ISSUE THREAD

**Issue by Fyb3roptik** [skjolber/external-nfc-api#11]
I have an NFC Reader/Writer that is USB (ARC122u). I am trying to test this out to work with my Pi. I am getting Native NFC is not available. How can I get this working?

Thanks

**Comment by skjolber** [comment]
@Fyb3roptik is your Pi running Android, extend the Activites like in the examples.

**Comment by Fyb3roptik** [comment]
It is running Android Things. I had to use a different library to get it working
