### ISSUE TITLE
Ionic Usage

### ISSUE THREAD

**Issue by MatthieuBarthel** [skjolber/external-nfc-api#13]
Hello,

I bought "External NFC Reader Service" application and I am trying to make it work with a Ionic app using @ionic-native/nfc (with phonegap-nfc plugin behind).

I have no knowledge in Android development and I don't know where to start, could you please point me in the right direction ?

Thank you :-)

**Comment by romainperret** [comment]
Hello, Up please! ;(
Thanks

**Comment by skjolber** [comment]
Hi, wire the app into phonegap-nfc, use the existing event handling and add events for reader connect/disconnect too.
