### ISSUE TITLE
How to use with React Native?

### ISSUE THREAD

**Issue by brampauwelyn** [skjolber/external-nfc-api#15]
Is it possible to access this API from React Native?

**Comment by skjolber** [comment]
I don't know. It works via Intents, so quite possible, with a custom adapter perhaps.

**Comment by brampauwelyn** [comment]
@skjolber 
Thx! I will try some things out.
When looking into the react-native docs, maybe this could work:
[https://facebook.github.io/react-native/docs/native-modules-android#sending-events-to-javascript](https://facebook.github.io/react-native/docs/native-modules-android#sending-events-to-javascript)

**Comment by skjolber** [comment]
Perhaps; if you get hold of an existing (built-in) NFC integration plugin, it is just 'more of the same'.

**Comment by halindrome** [comment]
@brampauwelyn did you get this to work?   I am considering something similar.
