### ISSUE TITLE
Can't Read NDEF Message AC122U Card Mifare Classic 

### ISSUE THREAD

**Issue by hasanbasri1993** [skjolber/external-nfc-api#16]
Bug i found Can't Read NDEF Message AC122U Card Mifare Classic 
Peripheral i use for Dev :

- HTC One  M9 - Android 9
- ACS ACR 122u 
- Card Mifare Classic

from this repo i was upgrade lib use ver 1.1.5 download from [acs](https://www.acs.com.hk/en/driver/3/acr122u-usb-nfc-reader/), compileSdkVersion and targetSdkVersion change to 26
I run **externalNFCService** use adb wireless to get logcat
Lastly i got error like this below picture, NDEF Message from my Card Mifare Classic  was Encoded by gototag.com can't read. in log UUID the Card was read perfect. Less NDEF Message

![nfc---](https://user-images.githubusercontent.com/6375150/69495558-d8cabe80-0efa-11ea-99a8-35e02264a78b.png)

**Comment by skjolber** [comment]
There is something wrong with Mifare Classic and ACR 122. I have not been able to make it work, however it did work with another reader having the exact same command se (1222L).

**Comment by hasanbasri1993** [comment]
ok thanks.
