### ISSUE TITLE
ExternalNFCHostApduService doesn't work on devices without an internal NFC reader

### ISSUE THREAD

**Issue by peteshand** [skjolber/external-nfc-api#2]
It seems like the ExternalNFCHostApduService doesn't work on devices without an internal NFC reader. Does this sound correct?

**Comment by skjolber** [comment]
Yes this is correct. The HCE application is targeting Android devices with internal NFC.

**Comment by peteshand** [comment]
But in theory is it possible to use this library along with your NFC service app with devices that don't have an internal NFC reader?

**Comment by skjolber** [comment]
The library enables connecting an external reader to a device with or without internal NFC. When doing so, the HCE app is intended as a demo client; for communications between the external reader ('server') and an HCE-enabled device ('client') in a typical 'customer (client)' + 'Point of Sale (server)' setup.

**Comment by peteshand** [comment]
Ok, cool.. thanks for the info
