### ISSUE TITLE
Using an ACR reader to emulate an ISO 7816 card app

### ISSUE THREAD

**Issue by mrtinps** [skjolber/external-nfc-api#20]
Hi,

With the current library, is it possible to use the ACR reader (for example the ACR122U) in card emulation mode to emulate an ISO 7816 compatible smart card application? If so, is there a code example for this? The only HCE code I could see was a test Android HCE app but I may be missing something.

Thanks,

Martin Patefield-Smith

**Comment by skjolber** [comment]
Try in combination with this: https://github.com/skjolber/external-nfc-api/blob/master/examples/client/src/main/java/com/github/skjolber/nfc/external/client/MainActivity.java#L364

**Comment by mrtinps** [comment]
Hi,

Thanks for this. What I'm trying to do is to use the reader itself as the target for another reader. Something like this:

https://salmg.net/2017/12/11/acr122upn532-nfc-card-emulation/

This looks like something over and above what your library does.

Thanks,

Martin

**Comment by skjolber** [comment]
I've only tried mobile-to-reader with HCE, but I guess anythings possible.
