### ISSUE TITLE
Feature Request: Enable WebNFC in Android Chrome with external NFC Reader

### ISSUE THREAD

**Issue by clst** [skjolber/external-nfc-api#28]
Hi,

We would have a use case for using external NFC Readers with a Chrome Website. The External NFC Service on Android can read and provide the data to apps but Chrome seems to ignore everything that is not an internal NFC reader.

Do you see any possibility of this ever working? I'd guess it's pretty much impossible without either support by Google or root.

**Comment by skjolber** [comment]
No, it is not possible to replace the native NFC service without a lot of effort + rooting devices.
