### ISSUE TITLE
device not detected

### ISSUE THREAD

**Issue by smoi** [skjolber/external-nfc-api#3]
Hi, 
i've tried both the client and the kiosk apps but the acr122 is not detected, the usb dialog doesn't come out.
I've also tried the acr122 app on play store and it works like a charm. 

Do you have any feedback on this?

Thanks

**Comment by smoi** [comment]
With further investigation I see that com.skjolberg.service.BackgroundUsbService is not found. Where is this supposed to be declaered? Inside the .aidl?

**Comment by skjolber** [comment]
The app https://play.google.com/store/apps/details?id=com.skjolberg.nfc.external is required for this to work (see top of documentation).
