### ISSUE TITLE
technology is not supported by the NFC Adapter

### ISSUE THREAD

**Issue by myrddraall** [skjolber/external-nfc-api#4]
When trying to connect to an UltralightC i get the following message:

> Connecting to this technology is not supported by the NFC adapter.

I've tried it with both the ARC122U-A9 Reader and the ARC1252U-A1

I'm running android 5.1.1 on an ODROID C2

```
Tag tag = (Tag)intent.getParcelableExtra(NfcAdapter.EXTRA_TAG);
NfcA nfca = NfcA.get(tag);
try {
    nfca.close();
    nfca.connect();
} catch (Exception e) {
 e.printStackTrace();
}
```

**Comment by skjolber** [comment]
I'm looking into more fault tolerance for reading initial info in ultralight tags, in case blocks cannot be read due to encryption.

**Comment by myrddraall** [comment]
Thanks for the quick reply. I'm working with an empty tags, they're completely fresh with nothing encrypted on it yet. The service seems to think that the readers don't support NFCA.

**Comment by skjolber** [comment]
I'm expecting to fix this within a week.

**Comment by skjolber** [comment]
I've made some progress, however seperating ultralight from ultralight c is a bit hairy

**Comment by myrddraall** [comment]
I don't know if its any help but nxp has released a new api called Taplinx https://www.mifare.net/en/products/tools/taplinx/

Its api is much cleaner especially in the tag detection area

**Comment by skjolber** [comment]
I'll look into it, seems like the licensing is much better (free).

**Comment by skjolber** [comment]
I did some changes for version 1.10 of the service, can you check whether they are working better?
