### ISSUE TITLE
HCE app can't connect to Basic app

### ISSUE THREAD

**Issue by YongTaek** [skjolber/external-nfc-api#5]
I have a acr1252u reader.
I want to use the reader for hce reader. So I tested with externalNFCHostCardEmulationClient and externalNFCClient. But no log was output for externalNFCHostCardEmulationClient.

When I check log in android studio, I saw "No reader supplied" log. Does this log relate to the problem?
What I have to do?

**Comment by skjolber** [comment]
Were you able to get the reader opened using the External NFC Service app main activity? Also, which Android device are you running?

**Comment by YongTaek** [comment]
I tested on Genymotion virtual device, api 22. And I get the reader opened. Also When I tag my phone to reader, I get a "present" message, too. But in onNfcIntentDetected, intent extra doesn't have NfcAdapter.EXTRA_TAG or sometimes have NfcAdapter.EXTRA_TAG but NfcTag.EXTRA_HOST_CARD_EMULATION is false.

**Comment by YongTaek** [comment]
I got reader opened in External NFC Service app. And I use Genymotion Virtual machine, api 22

**Comment by skjolber** [comment]
Can you paste all the relevant logs from android logcat? The no reader supplied might be that the reader detector is not working as expected.

**Comment by skjolber** [comment]
The ACR 1252 reacts somewhat differently when screen is locked (but lit) and screen is unlocked, I'm getting quite a few different ATRs actually, for the same devices.

I was able to tweak the settings however, to make it detect HCE all the time. See latest commit.

**Comment by YongTaek** [comment]
D/com.skjolberg.nfc.external.client.MainActivity: Tech android.nfc.tech.NfcA
D/com.skjolberg.nfc.external.client.MainActivity: Got NfcA with ATQA 4403 and sak 20
D/com.skjolberg.nfc.external.client.MainActivity: Tech android.nfc.tech.IsoDep
D/Test: com.skjolberg.nfc.NfcTag.extra.HOST_CARD_EMULATION: false
D/Test: com.skjolberg.nfc.NfcTag.extra.SLOT_NUMBER: 0
D/Test: com.skjolberg.nfc.NfcTag.extra.SERVICE_HANDLE: 2
D/com.skjolberg.nfc.external.client.MainActivity: Got android.nfc.tech.IsoDep

Sorry to late reply I got these log. Test log is log of extra key..
I got reader supplied now. but I didn't got that HOST_CARD_EMULATION is true..

I doesn't know ATR.. What is ATR? and I didn't try to tag when screen was locked

**Comment by YongTaek** [comment]
I see latest commit but I got a error in reader service.
`05-21 04:18:31.943 17840-17856/com.skjolberg.nfc.external E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                                        java.lang.AbstractMethodError: abstract method "int android.nfc.INfcTag.connect(int, int)"
                                                                            at android.nfc.INfcTag$Stub.onTransact(INfcTag.java:65)
                                                                            at android.os.Binder.execTransact(Binder.java:446)
                                                                        
                                                                        
                                                                        --------- beginning of crash
05-21 04:18:31.943 17840-17856/com.skjolberg.nfc.external E/AndroidRuntime: FATAL EXCEPTION: Binder_1
                                                                            Process: com.skjolberg.nfc.external, PID: 17840
                                                                            java.lang.AbstractMethodError: abstract method "int android.nfc.INfcTag.connect(int, int)"
                                                                                at android.nfc.INfcTag$Stub.onTransact(INfcTag.java:65)
                                                                                at android.os.Binder.execTransact(Binder.java:446)
`

**Comment by skjolber** [comment]
Can you try when the screen is locked, but lit. At a minimum, that should work.
