### ISSUE TITLE
External Reader Not Working after 24 Hour

### ISSUE THREAD

**Issue by NiveshShastri** [skjolber/external-nfc-api#6]
Hello Thomas,
I am trying to read and write on MIFARE UltraLight NFC card using  ACR 122U, its worked tomorrow but today its not.
Nivesh Shastri

**Comment by skjolber** [comment]
Hi,

do you have enough battery to power the external reader?

You'll have to tell me in more detail what the issue is.

**Comment by NiveshShastri** [comment]
Hello Thomas,
Thank you for quick reply.

Firstly I am not connect ACR 122U Device directly to my tablet, i have three port usb hub for 
connectivity .
I am not sure whats the problem, can you suggest me how to debug the issue.

**Comment by NiveshShastri** [comment]
Below are my logs:

com.skjolberg.nfc.external.client D/com.skjolberg.nfc.util.activity.NfcExternalDetectorActivity: Start receiving tag broadcasts
com.skjolberg.nfc.external.client D/com.skjolberg.nfc.util.activity.NfcExternalDetectorActivity: Start receiving reader broadcasts
com.skjolberg.nfc.external.client D/com.skjolberg.nfc.util.activity.NfcExternalDetectorActivity: Start receiving service broadcasts
com.skjolberg.nfc.external.client D/AbsListView: Get MotionRecognitionManager
com.skjolberg.nfc.external.client E/MotionRecognitionManager: mSContextService = null
com.skjolberg.nfc.external.client E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@bf24141
com.skjolberg.nfc.external.client D/com.skjolberg.nfc.util.activity.NfcDetectorActivity: Ignore action android.intent.action.MAIN
com.skjolberg.nfc.external.client D/ViewRootImpl: #1 mView = 11-06 15:13:52.419 28225-28225/com.skjolberg.nfc.external.client D/SecWifiDisplayUtil: Metadata value : SecSettings2
com.skjolberg.nfc.external.client D/ViewRootImpl: #1 mView = android.widget.LinearLayout{29bf427 V.E...... ......I. 0,0-0,0}
com.skjolberg.nfc.external.client D/mali_winsys: new_window_surface returns 0x3000,  [1200x1920]-format:1
com.skjolberg.nfc.external.client D/mali_winsys: new_window_surface returns 0x3000,  [342x66]-format:1
com.skjolberg.nfc.external.client D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 36 - 0, 0) vi=Rect(0, 36 - 0, 0) or=1
com.skjolberg.nfc.external.client D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1

**Comment by skjolber** [comment]
Hi, are you able to start the service and get the reader connected (does it has a light)? Not seeing anything in the log except from client code.

**Comment by NiveshShastri** [comment]
Even my reader is not connecting that's why i am unable to start service and i used only Client Module. which was working earlier.

**Comment by skjolber** [comment]
You'll have to get a permission dialog / light / beep on your reader before starting the service. Have you tried rebooting? Does the reader work if you plug it into your computer?

**Comment by NiveshShastri** [comment]
Dialog not appearing and i reboot device multiple times but not worked, reader light get on when I connect to computer.

**Comment by skjolber** [comment]
Hmm hard to say what the issue is, try connecting the cables in another order. Or use a plain OTG cable.

**Comment by NiveshShastri** [comment]
Hello Thomas,
I tried both way but nothing happened, can you suggest me another way of NFC r/w.

**Comment by skjolber** [comment]
So what does the log say when you plug the reader in and try to start the service?

**Comment by NiveshShastri** [comment]
Logs: 

**NfcDetectorActivity** 

11-08 10:46:15.281 5866-5866/? D/com.skjolberg.nfc.util.activity.NfcDetectorActivity: onCreate
11-08 10:46:15.281 5866-5866/? D/com.skjolberg.nfc.util.activity.NfcDetectorActivity: NFC feature not found
11-08 10:46:15.301 5866-5866/? D/com.skjolberg.nfc.util.activity.NfcDetectorActivity: Ignore action null

**NfcExternalDetectorActivity**

11-08 10:46:15.281 5866-5866/? D/com.skjolberg.nfc.util.activity.NfcExternalDetectorActivity: Start receiving tag broadcasts
11-08 10:46:15.281 5866-5866/? D/com.skjolberg.nfc.util.activity.NfcExternalDetectorActivity: Start receiving reader broadcasts
11-08 10:46:15.281 5866-5866/? D/com.skjolberg.nfc.util.activity.NfcExternalDetectorActivity: Start receiving service broadcasts

**Comment by skjolber** [comment]
Can you please get the log for the External NFC Reader Service app?
