### ISSUE TITLE
NFC ACR 122U Reader Not working

### ISSUE THREAD

**Issue by Dheerendra007** [skjolber/external-nfc-api#7]
Hello  skjolber,
I am using this sample. I connect NFC ACR 122U Reader by USB with my samsung galaxy tab A6 and run externalNFCClient application. Then app not connected with reader.
When i have installed External NFC Reader Service app(https://play.google.com/store/apps/details?id=com.skjolberg.nfc.external).Click on Start service now button then USb device connecttion window appear and reader connected.After connection i have again test sample then it's worked fine. 

So please provide any sample to connect  NFC ACR 122U Reader by USB.

**Comment by skjolber** [comment]
Hi, your request is a bit unclear. If the sample worked fine, what are you looking for?

**Comment by Dheerendra007** [comment]
external-nfc-api worked when i have installed External NFC Reader Service app 
from play store.(https://play.google.com/store/apps/details?id=com.skjolberg.nfc.external)
If i don't have this app then i am not able to connect NFC reader.

**Comment by Dheerendra007** [comment]
I want to be sample code that can be provide connection between NFC ACR 122U USB Reader and tablet.

**Comment by skjolber** [comment]
Ok, the google play app is necessary to use these examples. This is as intended.

**Comment by Dheerendra007** [comment]
Yes

**Comment by Dheerendra007** [comment]
So finally i need  google play app is necessary to use these examples.
Could you send sample code that can be provide connection between NFC ACR122U USB Reader and tablet.
